print("ยิดดีต้อนรับสู่โปรแกรมเครื่องคิดเลขแบบง่ายๆ")
a = int(input("input1 :"))
b = int(input("input2 :"))
print(a,"+",b,"=",(a+b))
print(a,"-",b,"=",(a-b))
print(a,"*",b,"=",(a*b))
print(a,"/",b,"=",(a/b))